[package]
name = "scan-nix"
version = "0.1.0"
authors = ["Aleksander Gondek <gondekaleksander@protonmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lorri = { git = "https://github.com/nix-community/lorri.git", rev = "f4b6a135e2efb18b3a679e3946d4d070a1c45a2c", version = "1.5.0" }
serde = { version = "1.0.127", features = ["derive"] }
serde_json = { version = "1.0.66" }
tempfile = { version = "3.2.0" }
walkdir = { version = "2.3.2" }
